instance_type    = "t3.medium"
region           = "eu-central-1"
ami_owner        = "099720109477"
source_ami_name  = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
vpc_name         = "vpc"
subnet_name      = "pub-subnet"